---
abstract: 'Various ancient e-mail related modules'
author:
  - 'Mark Overmeer <markov@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MailTools
no_index:
  directory:
    - t
    - inc
requires:
  Date::Format: '0'
  Date::Parse: '0'
  IO::Handle: '0'
  Net::Domain: '1.05'
  Net::SMTP: '1.03'
  Test::More: '0'
resources:
  homepage: http://perl.overmeer.net/CPAN/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/markov2/perl5-MailTools.git
version: '2.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.011'
